# Generated by Django 4.1.4 on 2022-12-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='valid_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
