# Generated by Django 4.1.4 on 2022-12-24 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_remove_subscription_valid_days_subscription_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 23, 20, 17, 34, 479203)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_paid',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
